name: yory.photo
favicon: null
layout_spectrum: 0.48164
typography_spectrum: 0.13773
title: よりフォト
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dee3e6'
    - '#0c0a0b'
    - '#3d414a'
    - '#abaaa6'
    - '#6c6f78'
  brandStrength: 0.5
  lightness: 0.805949485162273
  saturation: 0.9381780491676182
  rhythmicContrast: 0.5
purpose: []
