name: yory.photo
favicon: null
layout_spectrum: 0.7530071695800871
typography_spectrum: 0.8513170045334846
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.07151082414202392
  lightness: 0.805949485162273
  saturation: 0.9381780491676182
  rhythmicContrast: 0.4304532108362764
purpose: []
